config/routes.rb
Rails.application.routes.draw do
  resources :caves

  get 'page/map'

  root 'page#map'

end

app/models/cave.rb
class Cave < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :set_cafe, only: [:show, :edit, :update, :destroy]

  # GET /caves
  # GET /caves.json
  def index
    @caves = Cave.all
  end

  # GET /caves/1
  # GET /caves/1.json
  def show
    @cafe = Cave.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /caves/new
  def new
    @cafe = Cave.new
  end

  # GET /caves/1/edit
  def edit
  end

  # POST /caves
  # POST /caves.json
  def create
    @cafe = Cave.new(cafe_params)

    respond_to do |format|
      if @cafe.save
        format.html { redirect_to @cafe, notice: 'Cave was successfully created.' }
        format.json { render :show, status: :created, location: @cafe }
      else
        format.html { render :new }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caves/1
  # PATCH/PUT /caves/1.json
  def update
    respond_to do |format|
      if @cafe.update(cafe_params)
        format.html { redirect_to @cafe, notice: 'Cave was successfully updated.' }
        format.json { render :show, status: :ok, location: @cafe }
      else
        format.html { render :edit }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caves/1
  # DELETE /caves/1.json
  def destroy
    @cafe.destroy
    respond_to do |format|
      format.html { redirect_to caves_url, notice: 'Cave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafe
      @cafe = Cave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafe_params
      params.require(:cave).permit(:name, :description, :lat, :lon)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def map
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/caves/_form.html.erb
<%= form_for(@cafe) do |f| %>
  <% if @cafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafe.errors.count, "error") %> prohibited this cafe from being saved:</h2>

      <ul>
      <% @cafe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caves/edit.html.erb
<h1>Editing Cafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafe %> |
<%= link_to 'Back', caves_path %>

app/views/caves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Caves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Lat</th>
      <th>Lon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caves.each do |cafe| %>
      <tr>
        <td><%= cafe.name %></td>
        <td><%= cafe.description %></td>
        <td><%= cafe.lat %></td>
        <td><%= cafe.lon %></td>
        <td><%= link_to 'Show', cafe, remote: true %></td>
        <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
        <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Cave', new_cafe_path %>

<div id="map_show"></div>

app/views/caves/new.html.erb
<h1>New Cafe</h1>

<%= render 'form' %>

<%= link_to 'Back', caves_path %>

app/views/caves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cafe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cafe.description %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @cafe.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @cafe.lon %>
</p>

<%= link_to 'Edit', edit_cafe_path(@cafe) %> |
<%= link_to 'Back', caves_path %>

app/views/caves/show.js.erb
$('#map_show').html('').append('<div id="map"></div>');
$(function() { 

	var map = L.map('map').setView([<%= @cafe.lat %>, <%= @cafe.lon %>], 10);

	var OpenStreetMap_BlackAndWhite = L.tileLayer('http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png', {
		attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
	});
	OpenStreetMap_BlackAndWhite.addTo(map);


	var lat = '<%= @cafe.lat %>';
	var lon = '<%= @cafe.lon %>';
	console.log(lat + " " + lon);
	var marker = L.marker([lat, lon]).addTo(map);

	marker.bindPopup("<b><%= @cafe.name %></b><br><%= @cafe.description %>.").openPopup();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectJaskinie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/page/map.html.erb
<h1>Page#map</h1>
<p>Find me in app/views/page/map.html.erb</p>

<div id="map"></div>